# Generated by Django 4.1.3 on 2022-12-07 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicles.brand', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Серия',
                'verbose_name_plural': 'Серии',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('start_year', models.PositiveIntegerField(verbose_name='Начало производства')),
                ('end_year', models.PositiveIntegerField(verbose_name='Конец производства')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicles.series', verbose_name='Серия')),
            ],
        ),
    ]
