# Generated by Django 4.1.3 on 2022-12-07 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_series_generation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generation',
            options={'ordering': ['start_year'], 'verbose_name': 'Поколение', 'verbose_name_plural': 'Поколения'},
        ),
        migrations.AlterField(
            model_name='series',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series', to='vehicles.brand', verbose_name='Бренд'),
        ),
    ]
