# Generated by Django 4.1.3 on 2022-12-10 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_generation_options_alter_series_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generation',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generations', to='vehicles.series', verbose_name='Серия'),
        ),
    ]
